# DOCKERFILE for Rocky Control node
# Use RockyLinux 9.3 docker image
FROM rockylinux:9.3

# Install needed components for image
RUN dnf -y install openssh-server vim iptables iputils sudo ansible-core && dnf clean all

# Create needed directories, create ssh key and change root password
RUN mkdir -p /var/run/sshd && ssh-keygen -A && echo 'root:wordpass' | chpasswd

# Create ansible user and set password
RUN adduser ansible && echo "ansible:ansible" | chpasswd

# Create dirs if missing and add ansible user
RUN mkdir -p /etc/sudoers.d
RUN echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Enable password-based SSH login
RUN sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Copy keygen-tool and password file to ansible home folder
COPY keygen-tool.sh /home/ansible/keygen-tool.sh
COPY password.txt /home/ansible/password.txt

# Modify permissions for keygen-tool and password.txt
RUN chown ansible:ansible /home/ansible/keygen-tool.sh
RUN chmod +x /home/ansible/keygen-tool.sh
RUN chown ansible:ansible /home/ansible/password.txt


# Expose port 22 for ssh
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]