# DOCKERFILE for rocky nodes
# Use RockyLinux 9.3 docker image
FROM rockylinux:9.3

# Install needed components for image
RUN dnf -y install openssh-server vim iptables iputils sudo && dnf clean all

# Create needed directories, create ssh key and change root password
RUN mkdir -p /var/run/sshd && ssh-keygen -A && echo 'root:wordpass' | chpasswd

# Create ansible user and set password
RUN adduser ansible && echo "ansible:ansible" | chpasswd

# Create directories if missing and add ansible user
RUN mkdir -p /etc/sudoers.d
RUN echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible

# Enable password-based SSH login
RUN sed -i 's/^#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose port 22 for ssh
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]